const state={payload:null,pulls:[],selected:null,overviewTab:"pulls",analysisTag:"placement",filter:"all",separate:true,sortAsc:true,tab:"survival"};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const num=v=>Number(v||0).toLocaleString("zh-CN");
const row=()=>state.selected==null?null:state.pulls[state.selected];
function playerCell(ref){return`<span style="color:${ref?.classColor||'#fff'}">${esc(ref?.player||ref?.name||'—')}</span>`}
function spellLink(id,name){return id?`<a href="https://www.wowhead.com/spell=${id}" data-wowhead="spell=${id}">${esc(name||id)}</a>`:esc(name||'—')}
function phaseKey(r){if(r.isKill)return"击杀";return({P1:"P1 · 灵魂之井","苏醒仪式":"P1.5 · 苏醒仪式",P2:"P2 · 火焰刑场",狂暴:"狂暴 · 解缚之怒"}[r.wipePhase]||r.wipePhase||"未分类")}
const phaseOrder=["击杀","P1 · 灵魂之井","P1.5 · 苏醒仪式","P2 · 火焰刑场","狂暴 · 解缚之怒","未分类"];
function phaseColor(r){return r.isKill?"#55dd8a":r.wipePhase?.includes("狂暴")?"#ff6578":r.wipePhase?.includes("P2")?"#a98bff":r.wipePhase?.includes("仪式")?"#e6a244":"#339ddb"}
function placementLabel(p){const label=p?.placementEstimate||"等待坐标";if(label==="靠边候选")return"贴边";if(label==="内场候选")return"未贴边";if(label.includes("窗口外"))return"坐标偏移过大";return label}
function orderedRows(){return state.pulls.map((r,index)=>({r,index})).filter(x=>state.filter!=="wipes"||!x.r.isKill).sort((a,b)=>(a.r.startTimeIso||`${a.r.date}-${a.r.fightID}`).localeCompare(b.r.startTimeIso||`${b.r.date}-${b.r.fightID}`)*(state.sortAsc?1:-1))}
function totalTime(items){const total=Math.round(items.reduce((s,x)=>s+Number(x.r.durationMs||0),0)/1000);return`${Math.floor(total/60)}:${String(total%60).padStart(2,"0")}`}
function pullTile(x){const r=x.r,p=r.isKill?100:Math.max(5,100-Number(r.bossPercentage||0));return`<button class="pull-tile ${r.isKill?"kill-tile":""}" style="--progress:${p}%;--phase-color:${phaseColor(r)}" data-pull="${x.index}"><div class="pull-percent">${r.isKill?"KILL":`${Number(r.bossPercentage).toFixed(0)}%`}<small>${esc(r.wipePhase)}</small></div><div class="pull-copy"><b>P${esc(r.fightID)} · ${esc(r.duration)}</b><small>${esc(r.startClock||r.date)}</small></div></button>`}
function renderOverviewTabs(){document.querySelectorAll("[data-overview-tab]").forEach(b=>b.classList.toggle("active",b.dataset.overviewTab===state.overviewTab));$("pullsView").classList.toggle("hidden",state.overviewTab!=="pulls");$("analysisView").classList.toggle("hidden",state.overviewTab!=="analysis")}
function renderOverview(){renderOverviewTabs();const items=orderedRows(),kills=state.pulls.filter(r=>r.isKill).length,wipes=state.pulls.length-kills,last=[...state.pulls].sort((a,b)=>(a.startTimeIso||"").localeCompare(b.startTimeIso||"")).slice(-1)[0];$("wipesFilter").textContent=`全部灭团 (${wipes})`;$("allFilter").textContent=`全部战斗 (${kills} 击杀, ${wipes} 灭团)`;$("wipesFilter").classList.toggle("active",state.filter==="wipes");$("allFilter").classList.toggle("active",state.filter==="all");$("lastPull").innerHTML=last?`最后一场 · <span class="${last.isKill?"kill":"wipe"}">${last.isKill?"击杀":`${Number(last.bossPercentage).toFixed(2)}%`}</span> · ${esc(last.duration)} · ${esc(last.startClock)}`:"尚未载入";if(!items.length){$("pullBoard").innerHTML='<div class="empty">当前筛选没有战斗。</div>'}else{const groups=state.separate?[...new Set(items.map(x=>phaseKey(x.r)))].sort((a,b)=>phaseOrder.indexOf(a)-phaseOrder.indexOf(b)).map(k=>[k,items.filter(x=>phaseKey(x.r)===k)]):[["全部 Pull",items]];$("pullBoard").innerHTML=groups.map(([key,rows])=>`<section class="phase-group"><div class="phase-heading"><h2>${esc(key)}</h2><span class="phase-total">${rows.filter(x=>!x.r.isKill).length} 次灭团 · ${totalTime(rows)}</span></div><div class="pull-tiles">${rows.map(pullTile).join("")}</div></section>`).join("");document.querySelectorAll("[data-pull]").forEach(b=>b.onclick=()=>openPull(Number(b.dataset.pull)))}renderCrossAnalysis()}
function issueData(){const out={placement:[],barrage:[],invoke:[],avoidable:[]};state.pulls.forEach((fight,pullIndex)=>{const n=fight.nakzali||{};(n.essenceRend?.placements||[]).forEach((p,i)=>{const label=placementLabel(p);if(label!=="贴边")out.placement.push({fight,pullIndex,player:p.player,time:p.time,label,classColor:p.classColor})});(n.possessionBarrage?.rounds||[]).forEach(b=>{const verdicts=[...new Set((b.waves||[]).map(w=>w.verdict).filter(v=>v&&v!=="未见明显异常"))];if(verdicts.length)out.barrage.push({fight,pullIndex,player:b.target,time:b.time,label:verdicts.join(" / "),classColor:null})});(n.invokeInterrupts?.events||[]).forEach(v=>out.invoke.push({fight,pullIndex,player:v.player,time:v.time,label:v.phase,classColor:v.classColor}));Object.values(n.avoidableBoard||{}).flat().forEach(v=>out.avoidable.push({fight,pullIndex,player:v.name,spellID:v.spellID,spellName:v.spellName,label:v.spellName,hits:v.hitCount,damage:v.totalDamage,deaths:v.deathCount,classColor:v.classColor}))});return out}
function jumpButton(item,label){return`<button class="jump-link" data-jump-pull="${item.pullIndex}" data-jump-tab="${state.analysisTag==='avoidable'?'avoidable':state.analysisTag==='placement'?'essence':'tank'}">${esc(label)}</button>`}
function renderCrossAnalysis(){const data=issueData(),tags=[['placement','精华撕裂放置'],['barrage','附身弹幕'],['invoke','祈求影响'],['avoidable','可躲避伤害']];$("analysisTags").innerHTML=tags.map(([key,label])=>`<button data-analysis-tag="${key}" class="${state.analysisTag===key?"active":""}">${label}<span class="muted"> · ${data[key].length}</span></button>`).join("");document.querySelectorAll("[data-analysis-tag]").forEach(b=>b.onclick=()=>{state.analysisTag=b.dataset.analysisTag;renderCrossAnalysis()});const rows=(data[state.analysisTag]||[]).map(x=>{if(state.analysisTag==='placement')return[jumpButton(x,`Pull ${x.fight.fightID}`),x.time,playerCell(x),x.label];if(state.analysisTag==='avoidable')return[jumpButton(x,`Pull ${x.fight.fightID}`),playerCell(x),spellLink(x.spellID,x.spellName),x.hits,num(x.damage),x.deaths];return[jumpButton(x,`Pull ${x.fight.fightID}`),x.time,playerCell(x),x.label]});const headers={placement:["战斗","时间","玩家","放置"],barrage:["战斗","时间","目标","结论"],invoke:["战斗","时间","玩家","阶段"],avoidable:["战斗","玩家","技能","次数","总伤害","致死"]}[state.analysisTag];$("analysisContent").innerHTML=`<section class="panel issue-card"><h2>${tags.find(([k])=>k===state.analysisTag)?.[1]||''}</h2>${rows.length?simpleTable(headers,rows):'<div class="empty">没有对应记录。</div>'}</section>`;bindJumpLinks();if(window.$WowheadPower)window.$WowheadPower.refreshLinks()}
function bindJumpLinks(){document.querySelectorAll("[data-jump-pull]").forEach(b=>b.onclick=()=>openPull(Number(b.dataset.jumpPull),b.dataset.jumpTab||"survival"))}
function openPull(index,tab="survival"){state.selected=index;state.tab=tab;render();updateHash()}
function updateHash(){if(state.selected==null){history.replaceState(null,"",`${location.pathname}${location.search}${state.overviewTab==="analysis"?`#analysis=${state.analysisTag}`:""}`);return}const r=row(),parts=[`fight=${r.fightID}`];if(state.tab!=="survival")parts.push(`tab=${state.tab}`);history.replaceState(null,"",`${location.pathname}${location.search}#${parts.join("&")}`)}
function renderStats(){const r=row(),n=r.nakzali||{};$("detailTitle").textContent=`盘魂者内克扎利 · Pull ${r.fightID}`;$("detailMeta").textContent=`${r.difficultyName||"未知难度"} · ${r.isKill?"击杀":`灭团于 ${r.wipePhase}，Boss 剩余 ${Number(r.bossPercentage).toFixed(2)}%`} · ${r.date} ${r.startClock||""}`;$("wclLink").href=r.wclDeepLink;$("stats").innerHTML=[["战斗时长",r.duration],["结果",r.isKill?"KILL":`${Number(r.bossPercentage).toFixed(2)}%`],["精华撕裂",n.essenceRend?.placements?.length||0],["附身弹幕",n.possessionBarrage?.rounds?.length||0],["噬灭烈焰",n.hungeringPyre?.rounds?.length||0],["祈求影响",n.invokeInterrupts?.count||0]].map(([l,v])=>`<div class="stat"><strong>${esc(v)}</strong><span class="muted">${l}</span></div>`).join("")}
function simpleTable(headers,rows){return`<div class="scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function table(headers,rows){if(!rows.length)return'<div class="empty">本场没有对应事件。</div>';return simpleTable(headers.map(h=>h[0]),rows.map(r=>headers.map(h=>h[1](r))))}
function renderSurvival(){const s=row().survival||{},rows=s.timeline||[];return`<article class="card"><h3>死亡 / 战复时间线</h3><p class="muted">阵亡 ${s.deathCount||0} 次 · 战复 ${s.combatResCount||0} 次 · 战斗结束存活 ${s.survivorCount||0}/${s.rosterCount||0}</p>${table([["时间",x=>esc(x.time)],["类型",x=>x.kind==='combat_res'?'<span class="badge good">战复</span>':'<span class="badge warn">死亡</span>'],["玩家",x=>playerCell(x)],["原因 / 技能",x=>x.kind==='combat_res'?`${esc(x.source)} 使用 ${esc(x.ability)}`:x.deathCause==='fall'?`跌落${x.abilityID?`（关联 ${spellLink(x.abilityID,x.ability)}）`:''}`:spellLink(x.abilityID,x.ability)]],rows)}</article>`}
function renderEssence(){const rows=row().nakzali?.essenceRend?.placements||[];return`<article class="card"><h3>精华撕裂放置</h3>${table([["时间",x=>esc(x.time)],["玩家",x=>playerCell(x)],["距中心",x=>x.distanceFromCenterYards==null?'—':`${x.distanceFromCenterYards}码`],["坐标偏移",x=>x.sampleOffsetMs==null?'无':`${x.sampleOffsetMs>0?'+':''}${x.sampleOffsetMs}ms`],["结果",x=>esc(placementLabel(x))]],rows)}</article>`}
function renderFlames(){const rows=row().nakzali?.hungeringPyre?.rounds||[];return`<article class="card"><h3>噬灭烈焰分摊 / 蛇形烈焰</h3><p class="muted">只展示分摊人员；同轮蛇形烈焰点名为未分摊组。</p>${table([["轮次",x=>`#${x.index}`],["时间",x=>esc(x.time)],["分摊人员",x=>(x.soakPlayerRefs||[]).map(playerCell).join('、')||esc((x.soakPlayersByDamage||[]).join('、')||'—')],["蛇形烈焰",x=>(x.slitheringFlameRefs||[]).map(playerCell).join('、')||esc((x.slitheringFlamePlayers||[]).join('、')||'—')]],rows)}</article>`}
function renderAvoidable(){const grouped={};Object.values(row().nakzali?.avoidableBoard||{}).flat().forEach(entry=>{(grouped[entry.spellID]=grouped[entry.spellID]||[]).push(entry)});return Object.entries(grouped).map(([spellID,rows])=>`<article class="card"><h3>${spellLink(Number(spellID),rows[0]?.spellName)}</h3>${table([["玩家",x=>playerCell(x)],["次数",x=>num(x.hitCount)],["总伤害",x=>num(x.totalDamage)],["致死",x=>num(x.deathCount)]],rows)}</article>`).join("")||'<div class="empty">本场没有可规避机制命中。</div>'}
function renderTank(){const tank=row().nakzali?.tankSwap||{};return`<article class="card"><h3>摄魂打击峰值</h3>${table([["坦克",x=>playerCell(x)],["最高层数",x=>x.peakStack]],tank.peakStacks||[])}</article><article class="card"><h3>每轮附身弹幕时的坦克层数</h3>${table([["轮次",x=>`#${x.index}`],["时间",x=>esc(x.time)],["弹幕目标",x=>esc(x.target||'—')],["两坦层数",x=>(x.tanks||[]).map(t=>`${playerCell(t)} ${t.stack}层`).join(' · ')]],tank.barrageStacks||[])}</article><article class="card"><h3>嘲讽时间线</h3>${table([["时间",x=>esc(x.time)],["坦克",x=>playerCell(x)],["技能",x=>spellLink(x.spellID,x.spell)],["目标",x=>esc(x.target||'—')]],tank.taunts||[])}</article><article class="card"><h3>坦克死亡</h3>${table([["时间",x=>esc(x.time)],["坦克",x=>playerCell(x)],["致死技能",x=>x.deathCause==='fall'?'跌落':spellLink(x.abilityID,x.ability)]],tank.tankDeaths||[])}</article>`}
function renderTab(){const renderers={survival:renderSurvival,essence:renderEssence,flames:renderFlames,avoidable:renderAvoidable,tank:renderTank};$("tabContent").innerHTML=(renderers[state.tab]||renderSurvival)();document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===state.tab));if(window.$WowheadPower)window.$WowheadPower.refreshLinks()}
function renderDetail(){renderStats();renderTab()}
function render(){const detail=state.selected!=null;$("overviewPage").classList.toggle("hidden",detail);$("detailPage").classList.toggle("hidden",!detail);detail?renderDetail():renderOverview()}
function parseHash(){const query=new URLSearchParams(location.search),raw=location.hash.replace(/^#/,""),p=new URLSearchParams(raw);if(p.has('analysis')){state.overviewTab='analysis';state.analysisTag=p.get('analysis')||'placement';return}const fight=Number(query.get('fight')||p.get('fight'));if(!fight)return;const index=state.pulls.findIndex(r=>Number(r.fightID)===fight);if(index>=0){state.selected=index;state.tab=p.get('tab')||'survival'}}
function load(payload){state.payload=payload;state.pulls=payload.data?.page1_wipeAnalysis||payload.data?.nakzaliPulls||[];state.selected=null;$("overviewError").textContent="";parseHash();render()}
async function importFile(e){try{load(JSON.parse(await e.target.files[0].text()))}catch(error){$("overviewError").textContent=`无法载入：${error.message}`}}
$("overviewFile").onchange=importFile;$("detailFile").onchange=importFile;$("backButton").onclick=()=>{state.selected=null;state.overviewTab='pulls';render();updateHash()};$("wipesFilter").onclick=()=>{state.filter='wipes';renderOverview()};$("allFilter").onclick=()=>{state.filter='all';renderOverview()};$("separatePhases").onchange=e=>{state.separate=e.target.checked;renderOverview()};$("sortButton").onclick=()=>{state.sortAsc=!state.sortAsc;$("sortButton").textContent=state.sortAsc?'时间正序':'时间倒序';renderOverview()};document.querySelectorAll("[data-overview-tab]").forEach(b=>b.onclick=()=>{state.overviewTab=b.dataset.overviewTab;renderOverview();updateHash()});document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderTab();updateHash()});
async function loadPath(path){load(await window.MythicReportRuntime.loadPayload(path))}const path=new URLSearchParams(location.search).get('json');if(path){$("backButton").onclick=()=>{location.href=`/frontend/report/overview.html?json=${encodeURIComponent(path)}`};loadPath(path).catch(e=>$("overviewError").textContent=e.message)}else renderOverview();
