const state={payload:null,descriptor:null,pulls:[],filter:"all",separate:true,sortAsc:true,sourcePath:""};
const $=id=>document.getElementById(id);
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));

function pullsOf(payload){
  const value=payload?.data?.page1_wipeAnalysis;
  if(Array.isArray(value))return value;
  if(value&&typeof value==="object")return[value];
  return Array.isArray(payload?.data?.nakzaliPulls)?payload.data.nakzaliPulls:[];
}
function orderedRows(){return state.pulls.map((pull,index)=>({pull,index})).filter(row=>state.filter!=="wipes"||!row.pull.isKill).sort((a,b)=>String(a.pull.startTimeIso||`${a.pull.date}-${a.pull.fightID}`).localeCompare(String(b.pull.startTimeIso||`${b.pull.date}-${b.pull.fightID}`))*(state.sortAsc?1:-1));}
function phaseKey(pull){return pull.isKill?"击杀":pull.wipePhase||pull.fightPhase||"未分类";}
function phaseRank(key){if(key==="击杀")return-1;if(/P1|阶段一|一阶段|第一/i.test(key))return10;if(/转场|间歇|仪式|静滞/i.test(key))return20;if(/P2|阶段二|二阶段|第二/i.test(key))return30;if(/P3|阶段三|三阶段|第三/i.test(key))return40;if(/狂暴|最终/i.test(key))return90;return50;}
function phaseColor(pull){if(pull.isKill)return"#55dd8a";const key=phaseKey(pull);if(/狂暴|最终|P3/i.test(key))return"#ff6578";if(/P2|阶段二|二阶段|第二/i.test(key))return"#a98bff";if(/转场|静滞|仪式|间歇/i.test(key))return"#e6a244";return"#339ddb";}
function totalTime(rows){const total=Math.round(rows.reduce((sum,row)=>sum+Number(row.pull.durationMs||0),0)/1000);return`${Math.floor(total/60)}:${String(total%60).padStart(2,"0")}`;}
function pullTile(row){const pull=row.pull,progress=pull.isKill?100:Math.max(4,100-Number(pull.bossPercentage||0));return`<button class="pull-tile ${pull.isKill?"kill-tile":""}" style="--progress:${progress}%;--phase-color:${phaseColor(pull)}" data-pull="${row.index}" type="button"><div class="pull-percent">${pull.isKill?"KILL":`${Number(pull.bossPercentage||0).toFixed(0)}%`}<small>${esc(pull.isKill?"完成":phaseKey(pull))}</small></div><div class="pull-copy"><b>Pull ${esc(pull.fightID??pull.id??row.index+1)} · ${esc(pull.duration||"")}</b><small>${esc(pull.startClock||pull.date||"")}</small></div></button>`;}
function groupRows(items){if(!state.separate)return[["全部 Pull",items]];const keys=[...new Set(items.map(row=>phaseKey(row.pull)))];keys.sort((a,b)=>phaseRank(a)-phaseRank(b));return keys.map(key=>[key,items.filter(row=>phaseKey(row.pull)===key)]);}
function openPull(index){const pull=state.pulls[index];if(!pull||!state.descriptor)return;location.href=window.MythicReportRuntime.detailUrl(state.descriptor,state.sourcePath,pull.fightID??pull.id??index+1);}
function render(){const items=orderedRows(),kills=state.pulls.filter(pull=>pull.isKill).length,wipes=state.pulls.length-kills,last=[...state.pulls].sort((a,b)=>String(a.startTimeIso||"").localeCompare(String(b.startTimeIso||""))).slice(-1)[0];$("wipesFilter").textContent=`全部灭团 (${wipes})`;$("allFilter").textContent=`全部战斗 (${kills} 击杀, ${wipes} 灭团)`;$("wipesFilter").classList.toggle("active",state.filter==="wipes");$("allFilter").classList.toggle("active",state.filter==="all");$("lastPull").innerHTML=last?`最后一场 · <span class="${last.isKill?"kill":"wipe"}">${last.isKill?"击杀":`${Number(last.bossPercentage||0).toFixed(2)}%`}</span> · ${esc(last.duration||"")} · ${esc(last.startClock||"")}`:"没有可显示的 Pull";$("pullBoard").innerHTML=items.length?groupRows(items).map(([key,rows])=>`<section class="phase-group"><div class="phase-heading"><h2>${esc(key)}</h2><span class="phase-total">${rows.filter(row=>!row.pull.isKill).length} 次灭团 · ${totalTime(rows)}</span></div><div class="pull-tiles">${rows.map(pullTile).join("")}</div></section>`).join(""):'<div class="empty">当前筛选没有战斗。</div>';document.querySelectorAll("[data-pull]").forEach(button=>button.onclick=()=>openPull(Number(button.dataset.pull)));}
async function load(){if(!state.sourcePath)throw new Error("公共概览需要从已生成或已导入的整场 JSON 进入。");state.payload=await window.MythicReportRuntime.loadPayload(state.sourcePath);state.descriptor=await window.MythicReportRuntime.loadDescriptor(state.payload);state.pulls=pullsOf(state.payload);const identity=window.MythicReportRuntime.identityOf(state.payload);$("bossName").textContent=identity.bossName||"全场战斗概览";$("raidName").textContent=[identity.version,state.payload.meta?.raidName||identity.raidKey].filter(Boolean).join(" · ");document.title=`${identity.bossName} · 全场战斗概览`;render();}
$("wipesFilter").onclick=()=>{state.filter="wipes";render();};$("allFilter").onclick=()=>{state.filter="all";render();};$("separatePhases").onchange=event=>{state.separate=event.target.checked;render();};$("sortButton").onclick=()=>{state.sortAsc=!state.sortAsc;$("sortButton").textContent=state.sortAsc?"时间正序":"时间倒序";render();};
state.sourcePath=new URLSearchParams(location.search).get("json")||"";load().catch(error=>$("error").textContent=error.message);
