(() => {
  const state={payload:null,pulls:[],pull:0,tab:"survival",sourcePath:""};
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const num=value=>Number(value||0).toLocaleString("zh-CN");
  const current=()=>state.pulls[state.pull]||null;
  const mechanics=()=>current()?.nymrissa_wavecaller||{};
  const player=row=>`<span class="player" style="color:${esc(row?.classColor||'#fff')}">${esc(row?.player||row?.name||'—')}</span>`;
  const players=rows=>(rows||[]).map(player).join("、")||"—";
  const spell=(id,name)=>`<a class="spell" href="https://www.wowhead.com/cn/spell=${Number(id)}" target="_blank" rel="noreferrer">${esc(name||`法术 ${id}`)}</a>`;
  function table(headers,rows){return rows?.length?`<div class="table-wrap"><table><thead><tr>${headers.map(item=>`<th>${esc(item)}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${cell??'—'}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`:'<div class="empty">这场战斗没有对应记录。</div>'}
  function renderStats(){const pull=current(),survival=pull?.survival||{};$("title").textContent=`尼姆瑞莎·唤潮者 · Fight ${pull?.fightID||'—'}`;$("meta").textContent=`${pull?.difficultyName||'未知难度'} · ${pull?.isKill?'击杀':`Boss 剩余 ${Number(pull?.bossPercentage||0).toFixed(2)}%`} · ${pull?.date||''} ${pull?.startClock||''}`;$("wclLink").href=pull?.wclDeepLink||"#";const items=[["战斗时长",pull?.duration||"—"],["结果",pull?.isKill?"KILL":`${Number(pull?.bossPercentage||0).toFixed(2)}%`],["深渊之雨",mechanics().abyssalRain?.rounds?.length||0],["冰霜弹幕",mechanics().frostBarrage?.rounds?.length||0],["阵亡",survival.deathCount||0],["结束存活",`${survival.survivorCount||0}/${survival.rosterCount||0}`]];$("stats").innerHTML=items.map(([label,value])=>`<div class="stat"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`).join("")}
  function renderTabs(){const definitions=state.payload?.meta?.tabDefinitions||[{key:"survival",label:"死亡与战复"}];if(!definitions.some(row=>row.key===state.tab))state.tab=definitions[0].key;$("tabs").innerHTML=definitions.map(row=>`<button class="cosmic-button ${row.key===state.tab?'active':''}" data-tab="${esc(row.key)}">${esc(row.label)}</button>`).join("");document.querySelectorAll("[data-tab]").forEach(button=>button.onclick=()=>{state.tab=button.dataset.tab;renderTabs();renderContent()})}
  function renderSurvival(){const data=current()?.survival||{};return`<section class="glass-panel panel"><h2>死亡与战复时间线</h2><p class="hint">按时间排列实际死亡和战复记录，便于对照当时正在发生的机制。</p>${table(["时间","事件","玩家","原因 / 技能"],(data.timeline||[]).map(row=>[esc(row.time),row.kind==='combat_res'?'<span class="badge good">战复</span>':'<span class="badge bad">死亡</span>',player(row),row.kind==='combat_res'?`${esc(row.source)} 使用 ${esc(row.ability)}`:spell(row.abilityID,row.ability)]))}</section>`}
  function renderRain(){const data=mechanics().abyssalRain||{};return`<section class="glass-panel panel"><h2>${spell(1260837,'深渊之雨')}</h2><p class="hint">展示每轮读条后 12 秒内的实际伤害；总量用于比较压力，不直接判责。</p>${table(["轮次","时间","命中次数","总伤害"],(data.rounds||[]).map(row=>[`#${row.index}`,esc(row.time),num(row.hitCount),num(row.totalDamage)]))}</section><section class="glass-panel panel"><h2>${spell(1277386,'浸湿')}最高层数</h2><p class="hint">浸湿会随战斗推进叠加，可用于解释后续团队伤害为什么越来越高。</p>${table(["玩家","最高层数","最后记录"],(data.drenched||[]).map(row=>[player(row),`<span class="badge">${row.maxStack} 层</span>`,esc(row.lastTime)]))}</section>`}
  function renderFrost(){const data=mechanics().frostBarrage||{};return`<section class="glass-panel panel"><h2>${spell(1257614,'冰霜弹幕')}轮次</h2><p class="hint">点名与撞球来自事件时间窗。当前版本不根据缺失的冰球位置或生命周期强行判断放球错误。</p>${table(["轮次","时间","被点名玩家","撞球 / 全团命中","事件涉及玩家"],(data.rounds||[]).map(row=>[`#${row.index}`,esc(row.time),players(row.targets),num(row.orbHitCount),players(row.handlers)]))}</section>`}
  function renderTransition(){const rows=mechanics().transitions||[];return`<section class="glass-panel panel"><h2>${spell(1284015,'诱惑水泡')}转场</h2><p class="hint">鱼人波次与脉动潮汐伤害用来定位转火慢、鱼人进入水泡后的压力，不把缺失的击杀归属算到个人。</p>${table(["轮次","开始时间","鱼人波次","脉动命中","脉动伤害"],rows.map(row=>[`#${row.index}`,esc(row.time),num(row.addWaveCount),row.pulsingHitCount?`<span class="badge bad">${num(row.pulsingHitCount)}</span>`:'<span class="badge good">0</span>',num(row.pulsingDamage)]))}</section>`}
  function damageTable(rows){return table(["玩家","技能","次数","总伤害","时间"],(rows||[]).map(row=>[player(row),spell(row.spellID,row.spellName),row.hitCount,num(row.totalDamage),(row.events||[]).map(event=>esc(event.time)).join("、")]))}
  function renderPressure(){const data=mechanics(),enrage=data.enrage||{};return`${enrage.triggered?`<section class="glass-panel panel alert"><h2>已进入 ${spell(1295086,'无尽潮汐')}</h2><p class="hint">首次记录：${esc(enrage.time)}。这通常意味着本体输出时间或转场效率不足。</p></section>`:`<section class="glass-panel panel ok"><h2>未记录无尽潮汐</h2><p class="hint">本场没有进入已知硬狂暴施法。</p></section>`}<section class="glass-panel panel"><h2>场地伤害记录</h2><p class="hint">残留冰霜与旋转漩涡属于可复核承伤；建议结合 WCL 回放确认当时路线。</p>${damageTable(data.hazardHits)}</section><section class="glass-panel panel"><h2>对坦压力</h2><p class="hint">冰刃乱舞 / 水流喷射按承伤目标汇总，用于检查换坦和个人减伤时机。</p>${damageTable(data.tankPressure)}</section>`}
  function renderContent(){const renderers={survival:renderSurvival,rain:renderRain,frost:renderFrost,transition:renderTransition,pressure:renderPressure};$("content").innerHTML=(renderers[state.tab]||renderSurvival)()}
  function render(){renderStats();renderTabs();renderContent()}
  function load(payload){state.payload=payload;state.pulls=[...(payload.data?.page1_wipeAnalysis||[])].sort((left,right)=>String(right.startTimeIso||"").localeCompare(String(left.startTimeIso||"")));const requested=Number(new URLSearchParams(location.search).get("fight"));const index=state.pulls.findIndex(row=>Number(row.fightID)===requested);state.pull=index>=0?index:0;state.tab=(payload.meta?.tabDefinitions||[])[0]?.key||"survival";$("pullSelect").innerHTML=state.pulls.map((row,index)=>`<option value="${index}">Fight ${row.fightID} · ${esc(row.date||'')} ${esc(row.startClock||'')} · ${row.isKill?'KILL':`${Number(row.bossPercentage||0).toFixed(2)}%`}</option>`).join("");$("pullSelect").value=String(state.pull);$("error").textContent=state.pulls.length?'':'分析结果中没有尼姆瑞莎战斗。';render()}
  $("pullSelect").onchange=event=>{state.pull=Number(event.target.value);state.tab=(state.payload?.meta?.tabDefinitions||[])[0]?.key||"survival";render()};
  $("fileInput").onchange=async event=>{try{load(JSON.parse(await event.target.files[0].text()))}catch(error){$("error").textContent=`无法载入：${error.message}`}finally{event.target.value=""}};
  const path=new URLSearchParams(location.search).get("json");state.sourcePath=path||"";if(path)$("overviewLink").href=`/frontend/report/overview.html?json=${encodeURIComponent(path)}`;if(path)window.MythicReportRuntime.loadPayload(path).then(load).catch(error=>$("error").textContent=error.message);else $("error").textContent="请从全场概览进入，或导入分析 JSON。";
})();
