(function(root){
  'use strict';
  const replay=root.VashnikReplay,esc=root.MechanicWorkbench.escape;
  const colors={1:'#fbd857',2:'#ff9739',3:'#d879ff',4:'#6de772',5:'#bceaff',6:'#4cb6ff',7:'#ff666f',8:'#e5e7eb'},symbols={1:'★',2:'●',3:'◆',4:'▼',5:'☾',6:'■',7:'×',8:'☠'};
  root.VashnikFieldAdapter=function(scene,scope,roundSelect,video=false){
    const p=scene.arenaProjection,project=point=>replay.project(point,p),bounds=()=>{
      if(scope.value==='full')return p.fullBounds;
      const b=p.combatBounds,f=p.fullBounds,pad=36;
      const x=Math.max(f.x,b.x-pad),y=Math.max(f.y,b.y-pad);
      return {x,y,w:Math.min(f.x+f.w,b.x+b.w+pad)-x,h:Math.min(f.y+f.h,b.y+b.h+pad)-y};
    };
    const polygon=points=>points.map(point=>{const q=project(point);return `${q.x},${q.y}`;}).join(' '),clock=ms=>`${(ms/1000).toFixed(1)}s`;
    return {video,handlesPlayers:true,project(point){const q=project(point),b=bounds();return {x:100*(q.x-b.x)/b.w,y:100*(q.y-b.y)/b.h};},renderMap(selected,filtered,cursor,config){
      const rounds=scene.pillarRounds||[],round=rounds.find(r=>r.index===Number(roundSelect.value))||rounds.findLast(r=>r.applicationTimeMs<=cursor)||rounds[0],b=bounds(),pillars=round?.markerEvidenceComplete?(round.pillars||[]).filter(p=>!p.estimated):[];
      const players=round?.players.filter(row=>(!config.actor||row.player===config.actor)&&(!config.problemOnly||row.problem))||[];
      const waveVisible=!config.layers.length||config.layers.some(l=>['光柱到位','波浪方向参考','瘟疫泡沫标记'].includes(l)),totemVisible=!config.layers.length||config.layers.includes('恶念图腾');
      const simulation=scene.totemReplay?.simulation||{widthYards:5,speedYardsPerSecond:20,rangeYards:80};
      const keys=new Set(round?.totemResult?.beforeKeys||[]),units=scene.totemReplay?.units||[],context=units.filter(u=>{const state=replay.totemState(u,cursor);return state!=='future'&&(state!=='completed'||cursor-u.castCompletions[0]<8000)&&(!['dead','despawned'].includes(state)||cursor-(u.deathTimeMs??u.despawnTimeMs)<1500);});
      const live=context.filter(u=>!['future','dead','despawned','completed'].includes(replay.totemState(u,cursor))),dead=units.filter(u=>keys.has(u.key)&&replay.totemState(u,cursor)==='dead'),casting=live.filter(u=>replay.totemState(u,cursor)==='casting'),completed=live.filter(u=>replay.totemState(u,cursor)==='completed'),unknown=live.filter(u=>!u.positions.length);
      const waves=replay.waves(waveVisible&&round?{...round,players}:null,cursor,simulation).map((w,i)=>{
        const [left,middle,right]=w.crest.map(project),near=project({x:(w.tail[0].x+w.tail[3].x)/2,y:(w.tail[0].y+w.tail[3].y)/2}),far=project({x:(w.tail[1].x+w.tail[2].x)/2,y:(w.tail[1].y+w.tail[2].y)/2}),curve=`M ${left.x} ${left.y} Q ${middle.x} ${middle.y} ${right.x} ${right.y}`;
        return `<g opacity="${w.fade}"><title>${esc(w.player)}，模拟推波，${simulation.widthYards} 码宽</title><defs><linearGradient id="waveTrail${i}" gradientUnits="userSpaceOnUse" x1="${near.x}" y1="${near.y}" x2="${far.x}" y2="${far.y}"><stop stop-color="#7ee55e" stop-opacity="0"/><stop offset="1" stop-color="#c9ffa2" stop-opacity=".55"/></linearGradient></defs><polygon points="${polygon(w.path)}" fill="#90e661" opacity=".06"/><polygon points="${polygon(w.tail)}" fill="url(#waveTrail${i})"/><polygon points="${polygon(w.head)}" fill="#d9ffbc" opacity=".45" filter="url(#waveGlow)"/><path d="${curve}" fill="none" stroke="#abff69" stroke-width="7" filter="url(#waveGlow)"/><path d="${curve}" fill="none" stroke="#efffc7" stroke-width="2"/></g>`;
      }).join('');
      const guides=waveVisible?players.filter(row=>cursor>=row.applicationTimeMs&&cursor<row.timeMs&&row.referenceAvailable&&row.ending!=='death'&&row.position).flatMap(row=>replay.axes.slice(0,2).map(axis=>{const track=scene.combatReplay?.units.find(u=>u.actorID===row.playerID),origin=track&&root.MechanicWorkbench.trackPosition(track,cursor)||row.position;const a=project({x:origin.x-axis.x*8000,y:origin.y-axis.y*8000}),z=project({x:origin.x+axis.x*8000,y:origin.y+axis.y*8000});return `<line x1="${a.x}" y1="${a.y}" x2="${z.x}" y2="${z.y}" stroke="#dffbb4" stroke-width="1" stroke-dasharray="5 6" opacity="${cursor<row.timeMs?.6:.18}"><title>${esc(row.player)}，垂直 X</title></line>`;})).join(''):'';
      const totems=totemVisible?context.filter(u=>replay.totemState(u,cursor)!=='future'&&u.positions.length).map(u=>{
        const status=replay.totemState(u,cursor),point=replay.totemPosition(u,cursor),q=project(point),gone=['dead','despawned'].includes(status),age=cursor-(u.deathTimeMs??u.despawnTimeMs);
        if(gone&&age>=1500)return '';
        const color=status==='completed'?'#ff7193':gone?'#ffcc80':'#bef578';
        return `<g data-key="totem:${u.key}" opacity="${gone?Math.max(0,1-age/1500):1}"><title>${esc(u.name)}，${status==='casting'?'正在读条':status==='completed'?'恶念已施放':gone?'日志记录消失':'存活'}</title><circle cx="${q.x}" cy="${q.y}" r="14" fill="${color}" opacity=".25" filter="url(#waveGlow)"/><rect x="${q.x-11}" y="${q.y-11}" width="22" height="22" rx="5" fill="#15221b" stroke="${color}" stroke-width="2"/><image href="/assets/raids/venomous_abyss/icons/venom-totem.png" x="${q.x-10}" y="${q.y-10}" width="20" height="20" style="clip-path:inset(0 round 4px)"/>${gone?`<path d="M ${q.x-8} ${q.y-8} l 16 16 m 0 -16 l -16 16" stroke="${color}" stroke-width="2"/>`:''}</g>`;
      }).join(''):'';
      const tracks=scene.combatReplay?.units.filter(u=>u.kind==='player')||[];
      const visible=tracks.length?tracks.map(u=>({u,point:root.MechanicWorkbench.trackPosition(u,root.MechanicWorkbench.lifeState(u,cursor).positionTime,scene.combatReplay.interpolateMaxGapMs)})):players.filter(r=>r.position&&cursor>=r.applicationTimeMs&&cursor<=r.timeMs+5000).map(r=>({u:{...r,key:r.playerID,name:r.player,color:r.classColor},point:r.position}));
      const hits=scene.events.filter(e=>e.spellID===1295798&&e.kind==='damage'&&cursor>=e.timeMs&&cursor-e.timeMs<650);
      const origins=visible.filter(({u,point})=>point&&(!config.actor||u.name===config.actor)).map(({u,point})=>{
        const q={...project(point),stale:point.stale},life=root.MechanicWorkbench.lifeState(u,cursor);
        const hit=hits.some(e=>(e.targetID??e.actorID)===u.actorID);
        return root.MechanicWorkbench.avatar(u,q,11,hit,life.dead,life.opacity);
      }).join('');
      const others='';
      const outside=players.filter(row=>row.position).filter(row=>{const q=project(row.position);return q.x<b.x||q.x>b.x+b.w||q.y<b.y||q.y>b.y+b.h;}).length,resultReached=round&&cursor>=round.totemResult?.resultTimeMs;
      return `<div class="vash-field" data-replay-field><svg viewBox="${b.x} ${b.y} ${b.w} ${b.h}" aria-label="瓦什尼克垂直 X 推波与图腾状态"><defs><filter id="pillarGlow"><feGaussianBlur stdDeviation="4"/></filter><filter id="waveGlow" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="3"/></filter><linearGradient id="waveFill" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#82dc4f" stop-opacity=".4"/><stop offset=".6" stop-color="#d7ffa3" stop-opacity=".8"/><stop offset="1" stop-color="#fff8c9"/></linearGradient></defs><image href="${esc(p.image)}" width="${p.imageWidth||p.fullBounds.w}" height="${p.imageHeight||p.fullBounds.h}" transform="${esc(p.imageTransform||'')}"/><g data-key="guides">${guides}</g><g data-key="waves">${waves}</g><g data-key="pillars">${pillars.map(row=>{const q=project(row),color=colors[row.icon]||'#fff';return `<g><title>${esc(row.name)}，${row.estimated?'截图估算':'WCL 放置记录'}，${Math.round(row.x)}, ${Math.round(row.y)}</title><circle cx="${q.x}" cy="${q.y}" r="17" fill="${color}" opacity=".2" filter="url(#pillarGlow)"/><circle cx="${q.x}" cy="${q.y}" r="13" fill="#080f1b" fill-opacity=".7" stroke="${color}" stroke-width="1.5" ${row.estimated?'stroke-dasharray="3 3"':''}/><text x="${q.x}" y="${q.y+6}" text-anchor="middle" fill="${color}" font-size="20">${symbols[row.icon]||'?'}</text></g>`;}).join('')}</g><g data-key="totems">${totems}</g><g data-key="players">${origins}</g></svg></div><div class="vash-result"><strong>${resultReached?'本批结果':'图腾状态'}，点名 #${round?.index||'—'}${round?.explosionReview?.length?'，恶念爆炸':''}</strong><span>本批初始 ${keys.size}</span><span class="totem-cleared">已记录死亡 ${dead.length}</span><span>仍存活 ${live.length}</span><span>读条 ${casting.length} / 已施放 ${completed.length}</span>${unknown.length?`<span class="totem-unknown">${unknown.length} 个存活图腾缺少坐标</span>`:''}</div><div class="mw-map-caption" ${video?'hidden':''}>${round?`点名 #${round.index}，${esc(round.time)}，${round.checked?'痛饮后第一批':round.cycleIndex?'第二批补救清场':'首波'}，${pillars.filter(row=>!row.estimated).length} 个日志光柱 / ${pillars.filter(row=>row.estimated).length} 个截图参考`:'没有光柱轮次数据'}${outside?`，${outside} 个放波位置在作战区外，请切换完整场地`:''}<br>垂直 X，有效宽度约 ${simulation.widthYards} 码，动画速度 ${simulation.speedYardsPerSecond} 码/秒、射程 ${simulation.rangeYards} 码为模拟参数。图腾状态使用真实日志时间；场地对齐与虚线光柱仍为估算。</div>${!video&&totemVisible&&context.length?`<details class="vash-totem-list"><summary>本批图腾实例，存活与消失明细</summary><div>${context.map(u=>{const status=replay.totemState(u,cursor),label={future:'尚未出现',dead:'死亡',despawned:'消失',casting:'读条中',completed:'恶念已施放',alive:'存活'}[status];return `<span class="badge ${status==='dead'?'good':status==='completed'?'bad':''}" title="${esc(u.name)}，召唤 ${clock(u.spawnTimeMs??u.firstSeenTimeMs)}${u.deathTimeMs!=null?'，死亡 '+clock(u.deathTimeMs):''}">${u.key}，${label}${!u.positions.length?'，无坐标':''}</span>`;}).join('')}</div><p class="hint">${esc(scene.totemReplay.positionNote)} ${esc(round?.totemResult?.note||'')}</p></details>`:''}`;
    }};
  };
})(window);
